//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorServiceProxyClient.CalculatorWinServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/CalculatorService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorWinServiceReference.ISimpleCalculator")]
    public interface ISimpleCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/AddNumbers", ReplyAction="http://tempuri.org/ISimpleCalculator/AddNumbersResponse")]
        double AddNumbers(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/AddNumbers", ReplyAction="http://tempuri.org/ISimpleCalculator/AddNumbersResponse")]
        System.Threading.Tasks.Task<double> AddNumbersAsync(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/SubtractNumbers", ReplyAction="http://tempuri.org/ISimpleCalculator/SubtractNumbersResponse")]
        double SubtractNumbers(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/SubtractNumbers", ReplyAction="http://tempuri.org/ISimpleCalculator/SubtractNumbersResponse")]
        System.Threading.Tasks.Task<double> SubtractNumbersAsync(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/MultplyNumbers", ReplyAction="http://tempuri.org/ISimpleCalculator/MultplyNumbersResponse")]
        double MultplyNumbers(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/MultplyNumbers", ReplyAction="http://tempuri.org/ISimpleCalculator/MultplyNumbersResponse")]
        System.Threading.Tasks.Task<double> MultplyNumbersAsync(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/DivideNumbers", ReplyAction="http://tempuri.org/ISimpleCalculator/DivideNumbersResponse")]
        double DivideNumbers(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/DivideNumbers", ReplyAction="http://tempuri.org/ISimpleCalculator/DivideNumbersResponse")]
        System.Threading.Tasks.Task<double> DivideNumbersAsync(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISimpleCalculator/GetDataUsingDataContractResponse")]
        CalculatorServiceProxyClient.CalculatorWinServiceReference.CompositeType GetDataUsingDataContract(CalculatorServiceProxyClient.CalculatorWinServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISimpleCalculator/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<CalculatorServiceProxyClient.CalculatorWinServiceReference.CompositeType> GetDataUsingDataContractAsync(CalculatorServiceProxyClient.CalculatorWinServiceReference.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleCalculatorChannel : CalculatorServiceProxyClient.CalculatorWinServiceReference.ISimpleCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleCalculatorClient : System.ServiceModel.ClientBase<CalculatorServiceProxyClient.CalculatorWinServiceReference.ISimpleCalculator>, CalculatorServiceProxyClient.CalculatorWinServiceReference.ISimpleCalculator {
        
        public SimpleCalculatorClient() {
        }
        
        public SimpleCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double AddNumbers(double number1, double number2) {
            return base.Channel.AddNumbers(number1, number2);
        }
        
        public System.Threading.Tasks.Task<double> AddNumbersAsync(double number1, double number2) {
            return base.Channel.AddNumbersAsync(number1, number2);
        }
        
        public double SubtractNumbers(double number1, double number2) {
            return base.Channel.SubtractNumbers(number1, number2);
        }
        
        public System.Threading.Tasks.Task<double> SubtractNumbersAsync(double number1, double number2) {
            return base.Channel.SubtractNumbersAsync(number1, number2);
        }
        
        public double MultplyNumbers(double number1, double number2) {
            return base.Channel.MultplyNumbers(number1, number2);
        }
        
        public System.Threading.Tasks.Task<double> MultplyNumbersAsync(double number1, double number2) {
            return base.Channel.MultplyNumbersAsync(number1, number2);
        }
        
        public double DivideNumbers(double number1, double number2) {
            return base.Channel.DivideNumbers(number1, number2);
        }
        
        public System.Threading.Tasks.Task<double> DivideNumbersAsync(double number1, double number2) {
            return base.Channel.DivideNumbersAsync(number1, number2);
        }
        
        public CalculatorServiceProxyClient.CalculatorWinServiceReference.CompositeType GetDataUsingDataContract(CalculatorServiceProxyClient.CalculatorWinServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<CalculatorServiceProxyClient.CalculatorWinServiceReference.CompositeType> GetDataUsingDataContractAsync(CalculatorServiceProxyClient.CalculatorWinServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
